List<Map<String, String>> dados = [
  {
    'id': '0',
    'foto':
        'https://media.istockphoto.com/id/1396403999/pt/foto/look-to-the-future-with-hope.jpg?s=612x612&w=is&k=20&c=oIRcJ6M0moRzcSsDH1SfEYVZ0CtBlZwbY_lIdzx256c=',
    'email': 'veraalmeida@gmail.com',
    'nomeCompleto': 'Vera Almeida',
    'dataNascimento': '07/02/1990',
    'idade': '33',
    'altura': '1,75',
    'peso': '74',
    'genero': 'Feminino',
    'profissao': 'Professora 07:00 - 17:00',
    'estadoCivil': 'Solteira',
    'etnia': 'Caucasiana',
    'religiao': 'Cristã',
    'naturalidade': 'Brasileira',
    'endereco': 'Rua Amado Batista',
    'complemento': 'Hotel',
    'bairro': 'Bairro Roseira',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneResidencial': '3633-9425',
    'telefoneCelular': '19 98990-2233',
    'escolaridade': 'Ensino Superior completo',
    'trabalhaAtualmente': 'Sim',
    'trabalhoAtivoParado': 'Parado',
    'habitos': 'Usar muito as Redes Sociais',
    'rendaFamiliar': '15 mil reais',
    'pressaoArterial': '1',
    'frequenciaCardiaca': '1',
    'glicemiaCapilar': '1',
    'pulso': '1',
    'temperatura': '1',
    'saturacao': '1',
    'frequenciaRespiratoria': '1',
    'dores': '1',
    'queixaPrincipal': '1',
    'patologias': '1',
    'antecedentes': '1',
    'condicoesGerais': '1',
    'marcapasso': '1',
    'anticoncepcional': '1',
    'cicloMenstrual': '1',
    'gestante': '1',
    'filhos': '1',
    'alergias': '1',
    'proteses': '1',
    'sono': '1',
    'funcionamentoIntestinal': '1',
    'eliminacaoFisiologica': '1',
    'locomocao': '1',
    'tendenciaGanhoPeso': '1',
    'efGeral': '1',
    'efOlhos': '1',
    'efPescoco': '1',
    'estadoHigiene': '1',
    'fumante': '1',
    'frequenciaAlcoolica': '1',
  },
  {
    'id': '1',
    'foto':
        'https://media.istockphoto.com/id/1389348844/pt/foto/studio-shot-of-a-beautiful-young-woman-smiling-while-standing-against-a-grey-background.jpg?s=2048x2048&w=is&k=20&c=ZQVoPZnoApyV0vPa2C8469IdsWczQ5qR4NAOl43_b8Q=',
    'email': 'patriciaSilva@gmail.com',
    'nomeCompleto': 'Patricia Silva',
    'dataNascimento': '07/02/1990',
    'idade': '33',
    'altura': '1,75',
    'peso': '74',
    'genero': 'Feminino',
    'profissao': 'Professora 07:00 - 17:00',
    'estadoCivil': 'Solteira',
    'etnia': 'Caucasiana',
    'religiao': 'Cristã',
    'naturalidade': 'Brasileira',
    'endereco': 'Rua Amado Batista',
    'complemento': 'Hotel',
    'bairro': 'Bairro Roseira',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneResidencial': '3633-9425',
    'telefoneCelular': '19 98990-2233',
    'escolaridade': 'Ensino Superior completo',
    'trabalhaAtualmente': 'Sim',
    'trabalhoAtivoParado': 'Parado',
    'habitos': 'Usar muito as Redes Sociais',
    'rendaFamiliar': '15 mil reais',
    'pressaoArterial': '22',
    'frequenciaCardiaca': '22',
    'glicemiaCapilar': '22',
    'pulso': '22',
    'temperatura': '22',
    'saturacao': '22',
    'frequenciaRespiratoria': '22',
    'dores': '22',
    'queixaPrincipal': '22',
    'patologias': '22',
    'antecedentes': '22',
    'condicoesGerais': '22',
    'marcapasso': '22',
    'anticoncepcional': '22',
    'cicloMenstrual': '22',
    'gestante': '22',
    'filhos': '22',
    'alergias': '22',
    'proteses': '22',
    'sono': '22',
    'funcionamentoIntestinal': '22',
    'eliminacaoFisiologica': '22',
    'locomocao': '22',
    'tendenciaGanhoPeso': '22',
    'efGeral': '22',
    'efOlhos': '22',
    'efPescoco': '22',
    'estadoHigiene': '22',
    'fumante': '22',
    'frequenciaAlcoolica': '22',
  }
];
